### ISSUE TITLE
Redirect user back to the page where they started, after authentication

### ISSUE THREAD

**Issue by mikaelhg** [micronaut-projects/micronaut-oauth2#16]
When users enter a OAuth2-secured application through a link to a particular page or resource, they expect to continue using the application from that page, after having gone through authentication, rather than to be redirected to the application root URL.

This is how Spring OAuth2 behaves, as well as most authentication schemes I'm aware of.

Please implement this in micronaut-oauth2, and tell us roughly how we should devise a future-proof workaround, while waiting for the feature.

**Comment by jameskleeh** [comment]
This has been implemented
